import React, { useState } from 'react';
import { useApp } from '../../context/AppContext';
import { AppSidebar } from '../layout/AppSidebar';
import { MOCK_CLIENTS } from '../../data/mockData';
import type { ClientProfile, SuitabilityReportRecord } from '../../types';
import { exportSuitabilityReportPdf } from '../../utils/suitabilityPdfGenerator';
import {
  Briefcase, ChevronRight, FileText, Download, CheckCircle2,
  Clock, AlertTriangle, X, ShieldCheck, BarChart2
} from 'lucide-react';

/* ─── Suitability Report Preview Modal ────────────────────────────────────── */
function SuitabilityReportModal({
  report,
  onClose,
  onAcknowledge,
}: {
  report: SuitabilityReportRecord;
  onClose: () => void;
  onAcknowledge: (id: string) => void;
}) {
  const statusColor = {
    generated: 'bg-[#FFF8EE] text-[#92400E] border-[#F7E5C8]',
    reviewed:  'bg-[#EFF6FF] text-[#1E40AF] border-[#BFDBFE]',
    acknowledged: 'bg-[#E6F4EA] text-[#15803D] border-[#A7F3D0]',
  }[report.status];

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4" style={{ background: 'rgba(11,18,32,0.55)' }}>
      <div className="bg-white rounded-3xl shadow-2xl w-full max-w-2xl max-h-[92vh] overflow-y-auto border border-[#EDE9DF]">

        {/* Header */}
        <div className="flex items-start justify-between p-6 border-b border-[#EDE9DF]">
          <div>
            <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-[#C57D25] mb-1">
              <ShieldCheck className="w-4 h-4" />
              <span>Internal Compliance Reference Document</span>
            </div>
            <h2 className="text-xl font-extrabold text-[#14213D]">Investor Suitability Report</h2>
            <p className="text-xs text-[#64748B] mt-0.5">
              Not an official regulatory filing — for internal broker/RM review only.
            </p>
          </div>
          <button onClick={onClose} className="p-1.5 rounded-lg hover:bg-[#F1EFE9] cursor-pointer transition-colors">
            <X className="w-5 h-5 text-[#64748B]" />
          </button>
        </div>

        {/* Internal Disclaimer Banner */}
        <div className="mx-6 mt-4 bg-[#FFF8EE] border border-[#F7E5C8] rounded-xl p-3 text-xs text-[#63451B] font-semibold leading-relaxed">
          ⚠️ INTERNAL COMPLIANCE REFERENCE — FOR INTERNAL BROKER/RM REVIEW ONLY.
          THIS IS NOT AN OFFICIAL REGULATORY SUBMISSION TO SEBI, IEPF, OR ANY GOVERNMENT AUTHORITY.
        </div>

        <div className="p-6 space-y-5">

          {/* Report Meta */}
          <div className="grid grid-cols-2 gap-4">
            <div className="bg-[#FAF8F5] rounded-xl p-3 border border-[#EDE9DF]">
              <div className="text-[10px] uppercase text-[#64748B] font-bold">Client Name / ID</div>
              <div className="font-bold text-[#14213D] mt-0.5">{report.clientName}</div>
              <div className="text-xs text-[#64748B]">PAN Ref: {report.casPan}</div>
            </div>
            <div className="bg-[#FAF8F5] rounded-xl p-3 border border-[#EDE9DF]">
              <div className="text-[10px] uppercase text-[#64748B] font-bold">Generated By / At</div>
              <div className="font-bold text-[#14213D] mt-0.5">{report.generatedBy}</div>
              <div className="text-xs text-[#64748B]">{report.generatedAt}</div>
            </div>
            <div className="bg-[#FAF8F5] rounded-xl p-3 border border-[#EDE9DF]">
              <div className="text-[10px] uppercase text-[#64748B] font-bold">Risk Profile & Timeline</div>
              <div className="font-bold text-[#14213D] mt-0.5">{report.riskProfile}</div>
              <div className="text-xs text-[#64748B]">{report.investmentTimeline}</div>
            </div>
            <div className="bg-[#FAF8F5] rounded-xl p-3 border border-[#EDE9DF]">
              <div className="text-[10px] uppercase text-[#64748B] font-bold">AUM & Flags</div>
              <div className="font-bold text-[#14213D] mt-0.5">₹{report.totalValue.toLocaleString('en-IN')}</div>
              <div className={`text-xs font-bold ${report.redFlagsCount > 0 ? 'text-[#EF4444]' : 'text-[#2BB673]'}`}>
                {report.redFlagsCount} Active Flag{report.redFlagsCount !== 1 ? 's' : ''}
              </div>
            </div>
          </div>

          {/* Health Score */}
          <div>
            <div className="text-xs font-bold uppercase text-[#64748B] mb-2">Health Score Breakdown</div>
            <div className="flex items-center gap-3 mb-3">
              <div className={`text-3xl font-black ${report.healthScore >= 70 ? 'text-[#2BB673]' : 'text-[#C57D25]'}`}>
                {report.healthScore}
              </div>
              <div className="text-sm text-[#64748B]">/ 100 — Suitability Score</div>
            </div>
            <div className="space-y-2">
              {report.healthScoreFactors.map((f, i) => (
                <div key={i} className="flex items-start justify-between bg-[#FAF8F5] rounded-lg px-3 py-2 border border-[#EDE9DF]">
                  <div>
                    <div className="text-xs font-bold text-[#14213D]">{f.factor}</div>
                    <div className="text-[11px] text-[#64748B]">{f.reason}</div>
                  </div>
                  <div className={`text-sm font-black shrink-0 ml-4 ${f.penaltyOrBonus >= 0 ? 'text-[#2BB673]' : 'text-[#EF4444]'}`}>
                    {f.penaltyOrBonus >= 0 ? `+${f.penaltyOrBonus}` : f.penaltyOrBonus}
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Allocation */}
          <div>
            <div className="text-xs font-bold uppercase text-[#64748B] mb-2">Portfolio Allocation</div>
            <div className="grid grid-cols-4 gap-2">
              {[
                { label: 'Equities', pct: report.allocationSummary.equitiesPct, color: '#3B82F6' },
                { label: 'Mutual Funds', pct: report.allocationSummary.mfsPct, color: '#8B5CF6' },
                { label: 'Bonds', pct: report.allocationSummary.bondsPct, color: '#2BB673' },
                { label: 'REITs/InvITs', pct: report.allocationSummary.reitsPct, color: '#C57D25' },
              ].map(a => (
                <div key={a.label} className="bg-[#FAF8F5] rounded-xl p-3 border border-[#EDE9DF] text-center">
                  <div className="text-lg font-black" style={{ color: a.color }}>{a.pct}%</div>
                  <div className="text-[10px] text-[#64748B] font-semibold">{a.label}</div>
                </div>
              ))}
            </div>
          </div>

          {/* Red Flags */}
          <div>
            <div className="text-xs font-bold uppercase text-[#64748B] mb-2">
              Active Suitability Flags ({report.redFlagsList.length})
            </div>
            {report.redFlagsList.length === 0 ? (
              <div className="bg-[#E6F4EA] border border-[#A7F3D0] rounded-xl p-3 flex items-center gap-2 text-sm font-semibold text-[#15803D]">
                <CheckCircle2 className="w-4 h-4" />
                <span>No active mis-selling or suitability flags</span>
              </div>
            ) : (
              <div className="space-y-2">
                {report.redFlagsList.map((rf, i) => (
                  <div key={i} className="bg-[#FDF2F2] border border-[#FECACA] rounded-xl p-3">
                    <div className="font-bold text-[#991B1B] text-sm">🚩 {rf.title}</div>
                    <div className="text-xs text-[#7F1D1D] mt-1">{rf.description}</div>
                    <div className="text-xs text-[#14213D] mt-1.5 bg-white rounded-lg px-2 py-1 border border-[#FECACA]">
                      💡 {rf.suggestedAction}
                    </div>
                    {rf.sebiRuleRef && (
                      <div className="text-[10px] text-[#64748B] mt-1">Ref: {rf.sebiRuleRef}</div>
                    )}
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Acknowledgment Status */}
          <div className={`rounded-xl p-4 border ${statusColor}`}>
            <div className="flex items-center justify-between">
              <div>
                <div className="text-sm font-extrabold uppercase tracking-wide">
                  {report.status === 'acknowledged' ? '✓ Acknowledged & Reviewed' :
                   report.status === 'reviewed' ? '⏳ Under Review' :
                   '⏳ Pending Internal Acknowledgment'}
                </div>
                {report.status === 'acknowledged' && report.reviewedBy && (
                  <div className="text-xs mt-1 opacity-80">
                    Signed off by <strong>{report.reviewedBy}</strong> on {report.reviewedAt}
                  </div>
                )}
                {report.status === 'generated' && (
                  <div className="text-xs mt-1 opacity-70">
                    Generated but not yet reviewed by a Compliance Officer or RM.
                  </div>
                )}
              </div>
              {report.status !== 'acknowledged' && (
                <button
                  onClick={() => onAcknowledge(report.id)}
                  className="ml-4 px-4 py-2 bg-[#2BB673] text-white rounded-lg text-xs font-bold cursor-pointer shrink-0 hover:bg-[#1EA362] transition-colors"
                >
                  Acknowledge Review
                </button>
              )}
            </div>
          </div>

          {/* Actions */}
          <div className="flex gap-3 pt-1">
            <button
              onClick={() => exportSuitabilityReportPdf(report)}
              className="flex-1 flex items-center justify-center gap-2 py-2.5 bg-[#C57D25] text-white rounded-xl text-sm font-bold cursor-pointer hover:bg-[#B06C19] transition-colors"
            >
              <Download className="w-4 h-4" />
              Export as PDF
            </button>
            <button
              onClick={onClose}
              className="flex-1 flex items-center justify-center gap-2 py-2.5 bg-[#FAF8F5] border border-[#EDE9DF] text-[#14213D] rounded-xl text-sm font-bold cursor-pointer hover:bg-[#F1EFE9] transition-colors"
            >
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

/* ─── Broker Console Page ─────────────────────────────────────────────────── */
export const BrokerConsolePage: React.FC = () => {
  const { setCurrentPage, suitabilityReports, generateSuitabilityReport, acknowledgeReport } = useApp();
  const [selectedClient, setSelectedClient] = useState<ClientProfile>(MOCK_CLIENTS[0]);
  const [filterSeverity, setFilterSeverity] = useState<'all' | 'flagged'>('all');
  const [previewReport, setPreviewReport] = useState<SuitabilityReportRecord | null>(null);
  const [generatingFor, setGeneratingFor] = useState<string | null>(null);

  const filteredClients = filterSeverity === 'flagged'
    ? MOCK_CLIENTS.filter(c => c.flagCount > 0)
    : MOCK_CLIENTS;

  const getClientReport = (clientId: string) =>
    suitabilityReports.find(r => r.clientId === clientId);

  const handleGenerate = (client: ClientProfile) => {
    setGeneratingFor(client.id);
    setTimeout(() => {
      const report = generateSuitabilityReport(client.id, 'Amit Verma (RM)');
      setGeneratingFor(null);
      if (report) setPreviewReport(report);
    }, 600);
  };

  const handleAcknowledge = (reportId: string) => {
    acknowledgeReport(reportId, 'Amit Verma (RM)');
    // Update the preview to reflect new status
    setPreviewReport(prev => prev?.id === reportId
      ? { ...prev, status: 'acknowledged' as const, reviewedBy: 'Amit Verma (RM)', reviewedAt: new Date().toLocaleString('en-IN') }
      : prev
    );
  };

  return (
    <div className="min-h-screen bg-[#FAF8F5] flex text-[#14213D] font-sans overflow-x-hidden">
      <AppSidebar />

      <main className="flex-1 p-6 md:p-10 max-w-6xl overflow-y-auto">

        {/* Header */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-8 pb-6 border-b border-[#EDE9DF]">
          <div>
            <div className="flex items-center space-x-2 text-xs font-bold uppercase tracking-wider text-[#C57D25]">
              <Briefcase className="w-4 h-4" />
              <span>B2B Relationship Manager Workspace</span>
            </div>
            <h1 className="text-3xl font-extrabold text-[#14213D] mt-1">
              Broker / RM Console
            </h1>
            <p className="text-sm text-[#6B7280] mt-1">
              Manage assigned client portfolios, monitor mis-selling flags, and generate internal suitability reports.
            </p>
          </div>

          <div className="flex items-center space-x-2 bg-[#FFF8EE] px-3 py-1.5 rounded-xl border border-[#F7E5C8] text-sm font-semibold text-[#63451B]">
            <span>Assigned RM: Amit Verma</span>
          </div>
        </div>

        {/* Summary Strip */}
        <div className="grid grid-cols-3 gap-4 mb-6">
          <div className="bg-white rounded-2xl p-4 border border-[#EDE9DF]">
            <div className="text-xs text-[#8B93A7] font-semibold">Total Clients</div>
            <div className="text-2xl font-black text-[#14213D] mt-0.5">{MOCK_CLIENTS.length}</div>
          </div>
          <div className="bg-white rounded-2xl p-4 border border-[#EDE9DF]">
            <div className="text-xs text-[#8B93A7] font-semibold">Reports Generated</div>
            <div className="text-2xl font-black text-[#C57D25] mt-0.5">
              {suitabilityReports.length}
            </div>
          </div>
          <div className="bg-white rounded-2xl p-4 border border-[#EDE9DF]">
            <div className="text-xs text-[#8B93A7] font-semibold">Acknowledged</div>
            <div className="text-2xl font-black text-[#2BB673] mt-0.5">
              {suitabilityReports.filter(r => r.status === 'acknowledged').length}
            </div>
          </div>
        </div>

        {/* Client Roster & Inspector Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">

          {/* Client List (Left 2 cols) */}
          <div className="lg:col-span-2 space-y-4">

            <div className="flex items-center justify-between">
              <h2 className="font-bold text-base text-[#14213D]">
                Assigned Clients ({filteredClients.length})
              </h2>

              <div className="flex gap-2">
                <button
                  onClick={() => setFilterSeverity('all')}
                  className={`px-3.5 py-1.5 rounded-lg text-sm font-bold transition-all cursor-pointer ${
                    filterSeverity === 'all'
                      ? 'bg-[#14213D] text-white'
                      : 'bg-white text-[#6B7280] border border-[#EDE9DF]'
                  }`}
                >
                  All Clients
                </button>
                <button
                  onClick={() => setFilterSeverity('flagged')}
                  className={`px-3.5 py-1.5 rounded-lg text-sm font-bold transition-all cursor-pointer ${
                    filterSeverity === 'flagged'
                      ? 'bg-[#EF4444] text-white'
                      : 'bg-white text-[#6B7280] border border-[#EDE9DF]'
                  }`}
                >
                  Flagged Only
                </button>
              </div>
            </div>

            <div className="space-y-3">
              {filteredClients.map((client) => {
                const isSelected = selectedClient.id === client.id;
                const existingReport = getClientReport(client.id);
                const isGenerating = generatingFor === client.id;

                return (
                  <div
                    key={client.id}
                    onClick={() => setSelectedClient(client)}
                    className={`bg-white rounded-2xl p-5 border transition-all cursor-pointer shadow-xs ${
                      isSelected
                        ? 'border-2 border-[#C57D25] ring-2 ring-[#C57D25]/10'
                        : 'border-[#EDE9DF] hover:border-[#D4C7B5]'
                    }`}
                  >
                    <div className="flex items-center justify-between">
                      <div className="flex items-center space-x-4">
                        <div className="w-10 h-10 rounded-full bg-[#F6F4ED] text-[#C57D25] font-bold flex items-center justify-center border border-[#EDE9DF]">
                          {client.name.charAt(0)}
                        </div>
                        <div>
                          <h3 className="font-bold text-base text-[#14213D]">{client.name}</h3>
                          <p className="text-sm text-[#8B93A7] font-mono">PAN: {client.casPan}</p>
                        </div>
                      </div>

                      <div className="flex items-center space-x-4 text-right">
                        <div>
                          <div className="text-sm font-extrabold font-mono-num text-[#14213D]">
                            ₹{client.totalValue.toLocaleString('en-IN')}
                          </div>
                          <div className="text-xs text-[#8B93A7]">{client.riskProfile}</div>
                        </div>

                        <div className="text-center">
                          <span className={`px-2.5 py-0.5 rounded-full text-xs font-extrabold ${
                            client.healthScore >= 80
                              ? 'bg-[#E6F4EA] text-[#2BB673]'
                              : 'bg-[#FFF8EE] text-[#C57D25]'
                          }`}>
                            {client.healthScore}/100
                          </span>
                          {client.flagCount > 0 && (
                            <div className="text-xs font-bold text-[#EF4444] mt-0.5">
                              {client.flagCount} Alert{client.flagCount > 1 ? 's' : ''}
                            </div>
                          )}
                        </div>

                        <ChevronRight className="w-4 h-4 text-[#8B93A7]" />
                      </div>
                    </div>

                    {/* Report status badge under client row */}
                    {existingReport && (
                      <div className="mt-3 pt-3 border-t border-[#EDE9DF] flex items-center justify-between">
                        <div className={`flex items-center gap-1.5 text-xs font-semibold px-2.5 py-1 rounded-full border ${
                          existingReport.status === 'acknowledged'
                            ? 'bg-[#E6F4EA] text-[#15803D] border-[#A7F3D0]'
                            : 'bg-[#FFF8EE] text-[#92400E] border-[#F7E5C8]'
                        }`}>
                          {existingReport.status === 'acknowledged'
                            ? <><CheckCircle2 className="w-3 h-3" />Report Acknowledged</>
                            : <><Clock className="w-3 h-3" />Report Pending Review</>
                          }
                        </div>
                        <button
                          onClick={(e) => { e.stopPropagation(); setPreviewReport(existingReport); }}
                          className="text-xs text-[#C57D25] font-bold hover:underline cursor-pointer flex items-center gap-1"
                        >
                          <FileText className="w-3 h-3" /> View Report
                        </button>
                      </div>
                    )}
                  </div>
                );
              })}
            </div>

          </div>

          {/* Single Client Detail Inspector (Right 1 col) */}
          <div className="bg-white rounded-3xl p-6 border border-[#EDE9DF] shadow-xs h-fit sticky top-24 space-y-4">
            <div className="text-xs font-bold uppercase tracking-wider text-[#8B93A7] mb-1">Client Summary</div>
            <h3 className="text-xl font-extrabold text-[#14213D]">{selectedClient.name}</h3>

            <div className="space-y-3 text-sm">
              <div className="bg-[#FAF8F5] p-3 rounded-xl border border-[#EDE9DF]">
                <div className="text-[#8B93A7] text-xs">Email</div>
                <div className="font-semibold text-[#14213D]">{selectedClient.email}</div>
              </div>

              <div className="bg-[#FAF8F5] p-3 rounded-xl border border-[#EDE9DF]">
                <div className="text-[#8B93A7] text-xs">Risk Profile & Timeline</div>
                <div className="font-bold text-[#14213D]">{selectedClient.riskProfile}</div>
                <div className="text-xs text-[#64748B]">{selectedClient.investmentTimeline ?? 'Not specified'}</div>
              </div>

              <div className="bg-[#FAF8F5] p-3 rounded-xl border border-[#EDE9DF]">
                <div className="text-[#8B93A7] text-xs">Active Flag Issue</div>
                <div className="font-bold text-[#991B1B] text-sm">{selectedClient.topFlag}</div>
              </div>

              <div className="bg-[#FAF8F5] p-3 rounded-xl border border-[#EDE9DF]">
                <div className="text-[#8B93A7] text-xs">Last Statement Sync</div>
                <div className="font-medium text-[#475569]">{selectedClient.lastUpdated}</div>
              </div>

              {/* ── Generate Suitability Report ── */}
              {(() => {
                const existingReport = getClientReport(selectedClient.id);
                const isGenerating = generatingFor === selectedClient.id;
                if (existingReport) {
                  return (
                    <div className="space-y-2">
                      <button
                        onClick={() => setPreviewReport(existingReport)}
                        className="w-full py-2.5 bg-[#FAF8F5] border border-[#C57D25] text-[#C57D25] rounded-xl font-bold text-sm flex items-center justify-center gap-2 cursor-pointer hover:bg-[#FFF8EE] transition-colors"
                      >
                        <FileText className="w-4 h-4" />
                        View Suitability Report
                      </button>
                      <button
                        onClick={() => exportSuitabilityReportPdf(existingReport)}
                        className="w-full py-2.5 bg-white border border-[#EDE9DF] text-[#64748B] rounded-xl font-bold text-sm flex items-center justify-center gap-2 cursor-pointer hover:bg-[#FAF8F5] transition-colors"
                      >
                        <Download className="w-4 h-4" />
                        Export PDF
                      </button>
                    </div>
                  );
                }
                return (
                  <button
                    onClick={() => handleGenerate(selectedClient)}
                    disabled={isGenerating}
                    className="w-full py-2.5 bg-[#C57D25] hover:bg-[#B06C19] text-white rounded-xl font-bold transition-all shadow-xs cursor-pointer text-sm flex items-center justify-center gap-2 disabled:opacity-60"
                  >
                    <BarChart2 className="w-4 h-4" />
                    {isGenerating ? 'Generating…' : 'Generate Suitability Report'}
                  </button>
                );
              })()}

              <button
                onClick={() => setCurrentPage('explainability')}
                className="w-full py-2.5 bg-[#14213D] hover:bg-[#0B1220] text-white rounded-xl font-bold transition-all cursor-pointer text-sm flex items-center justify-center gap-2"
              >
                <AlertTriangle className="w-4 h-4" />
                Inspect Client Explainability
              </button>
            </div>
          </div>

        </div>

      </main>

      {/* Report Preview Modal */}
      {previewReport && (
        <SuitabilityReportModal
          report={previewReport}
          onClose={() => setPreviewReport(null)}
          onAcknowledge={handleAcknowledge}
        />
      )}
    </div>
  );
};
